### ISSUE TITLE
Command aliases

### ISSUE THREAD

**Issue by manningtelfer** [projectcitybuild/PCBridge#83]
Add command aliases to replicate/override essentials functionality.

E.g. for messaging, /msg aliases include:
* m
* w
* whisper
* t
* pm
* emsg
* epm
* tell
* etell
* whisper
* ewhisper

We probably don't need to replicate all of these but /m would be a good shorthanbd to include - then we can either override essentials or disable essentials messaging.

**Comment by freddyheppell** [comment]
also (if it's not already implemented) `/r` to whisper the last person who whispered you

**Comment by andyksaw** [comment]
I've added a lot here: #82 

Basically it now supports: `whisper`, `w, `msg`, `m`, `tell`, `t` and `pm`

The `e` I guess stands for "Essentials", which is pretty unnecessary anyway because Spigot registers both the original command (eg. `msg`) and a prefixed version in case of conflicts (eg. `pcbridge:msg`)
